apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    resource: cluster
  name: {{ .Values.DB_CONFIGMAP }}
data:
  dbname: "{{ .Values.DBName }}"
  host: "{{ .Values.Hostname }}"
  port: "{{ .Values.Port }}"
  sslmode: "{{ .Values.SSLMode }}"
  sslRootCertPath: "{{ .Values.SSLRootCertPath }}"
