{{- if .Values.deployBackendMocks -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: postgres-{{ .Chart.Name }}
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Values.DB_SECRET }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .Values.DB_SECRET }}
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: dbname
              name: {{ .Values.DB_CONFIGMAP }}
        image: postgres:10.4
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
          - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-{{ .Chart.Name }}
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-{{ .Chart.Name }}
  type: ClusterIP
{{- end }}
