apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secrets"
type: Opaque
data:
  go-mcp-host-secret: {{ .Values.GO_MCP_HOST_SECRET | b64enc }}
---
apiVersion: v1
data:
  password: {{ .Values.password | b64enc }}
  username: {{ .Values.username | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.DB_SECRET }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-jwt
type: Opaque
data:
  jwt.key: {{ .Values.DOWNLOAD_TICKET_JWT_KEY | b64enc }}
