apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secrets"
type: Opaque
data:
  go-svc-template-secret: {{ .Values.GO_SVC_TEMPLATE_SECRET | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-jwt-publickey-vega"
type: Opaque
data:
  jwtpublickey.pem: {{ .Values.VEGA_JWT_PUBLIC_KEY | b64enc }}
---
apiVersion: v1
data:
  password: {{ .Values.password | b64enc }}
  username: {{ .Values.username | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.DB_SECRET }}
type: Opaque
