apiVersion: v2
name: go-svc-template
version: <github_release>
home: https://github.com/gesundheitscloud/go-svc-template/
icon: https://avatars2.githubusercontent.com/u/25636481?v=3&s=200
description: Service for a certain purpose
