APP:
  GO_SVC_TEMPLATE_DEBUG: false
  GO_SVC_TEMPLATE_DEBUG_CORS: false
  GO_SVC_TEMPLATE_HOST: "ENV DEPENDENT"
  GO_SVC_TEMPLATE_TLS_CERT_SECRET_NAME: "ENV DEPENDENT"
  GO_SVC_TEMPLATE_PORT: 8080
  GO_SVC_TEMPLATE_CORS_HOSTS: "ENV DEPENDENT"
DB_CONFIGMAP: go-svc-template-db-connection
DB_SECRET: go-svc-template-db-credentials
REPLICAS: 1
