APP:
  DEBUG: false
  DEBUG_CORS: false
  HOST: "ENV DEPENDENT"
  TLS_CERT_SECRET_NAME: "ENV DEPENDENT"
  PORT: 9000
  CORS_HOSTS: "ENV DEPENDENT"
DB_CONFIGMAP: go-svc-template-db-connection
DB_SECRET: go-svc-template-db-credentials
REPLICAS: 1
