APP:
  DEBUG: false
  DEBUG_CORS: false
  HOST: "ENV DEPENDENT"
  TLS: "ENV DEPENDENT"
  PORT: 9000
  CORS_HOSTS: "ENV DEPENDENT"
  REMOTE_KEYS_URL: "https://login.microsoftonline.com/common/discovery/keys"
DB_CONFIGMAP: go-svc-template-db-connection
DB_SECRET: go-svc-template-db-credentials
REPLICAS: 1

# DB config
SSLMode: verify-full
SSLRootCertPath: /root.ca.pem
