DBName: go-svc-template
Hostname: postgres-go-svc-template.default.svc.cluster.local
Port: 5432
username: go-svc-template
password: go-svc-template
SSLMode: disable
GO_SVC_TEMPLATE_SECRET: super-secure
